### ISSUE TITLE
Debian Jessie: setup.py fails to install ruamel.yaml, but pip does not

### ISSUE THREAD

**Issue by cosinekitty** [gnuradio/pybombs#498] opened 2018-05-22 02:14 UTC
I was trying to follow the instructions for installing PyBOMBS so I could start experimenting with GNU Radio. I cloned this repo and followed the build instructions. The install failed with an "invalid environment marker" error shown at the bottom of the console listing below.  I have python 2.7.9 and 3.4.2 installed.  I am on Debian Jessie:
```
don@spearmint:~/github/pybombs$ python --version
Python 2.7.9
don@spearmint:~/github/pybombs$ python3 --version
Python 3.4.2
don@spearmint:~/github/pybombs$ uname -a
Linux spearmint 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux
```

Here is my console log.  Please let me know if there is any other diagnostic information I can provide.

```
don@spearmint:~/github$ git clone https://github.com/gnuradio/pybombs.git
Cloning into 'pybombs'...
remote: Counting objects: 5497, done.
remote: Total 5497 (delta 0), reused 0 (delta 0), pack-reused 5497
Receiving objects: 100% (5497/5497), 1.62 MiB | 356.00 KiB/s, done.
Resolving deltas: 100% (3800/3800), done.
Checking connectivity... done.
don@spearmint:~/github$ cd pybombs
don@spearmint:~/github/pybombs$ sudo python setup.py install
[sudo] password for don: 
running install
running bdist_egg
running egg_info
creating PyBOMBS.egg-info
writing requirements to PyBOMBS.egg-info/requires.txt
writing PyBOMBS.egg-info/PKG-INFO
writing top-level names to PyBOMBS.egg-info/top_level.txt
writing dependency_links to PyBOMBS.egg-info/dependency_links.txt
writing entry points to PyBOMBS.egg-info/entry_points.txt
writing manifest file 'PyBOMBS.egg-info/SOURCES.txt'
reading manifest file 'PyBOMBS.egg-info/SOURCES.txt'
writing manifest file 'PyBOMBS.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pybombs
copying pybombs/gitcache_manager.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/fetcher.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/inventory.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/main.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/recipe.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/requirer.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/config_manager.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/install_manager.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/tree_node.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/pb_exception.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/__init__.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/pb_logging.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/config_file.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/package_manager.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/recipe_manager.py -> build/lib.linux-x86_64-2.7/pybombs
copying pybombs/dep_manager.py -> build/lib.linux-x86_64-2.7/pybombs
creating build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/base.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/rebuild.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/autoconfig.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/run.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/prefix.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/inv.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/deploy.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/fetch.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/lint.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/git.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/__init__.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/recipes.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/install.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/remove.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/help.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/config.py -> build/lib.linux-x86_64-2.7/pybombs/commands
copying pybombs/commands/digraph.py -> build/lib.linux-x86_64-2.7/pybombs/commands
creating build/lib.linux-x86_64-2.7/pybombs/fetchers
copying pybombs/fetchers/base.py -> build/lib.linux-x86_64-2.7/pybombs/fetchers
copying pybombs/fetchers/wget.py -> build/lib.linux-x86_64-2.7/pybombs/fetchers
copying pybombs/fetchers/git.py -> build/lib.linux-x86_64-2.7/pybombs/fetchers
copying pybombs/fetchers/svn.py -> build/lib.linux-x86_64-2.7/pybombs/fetchers
copying pybombs/fetchers/__init__.py -> build/lib.linux-x86_64-2.7/pybombs/fetchers
copying pybombs/fetchers/file.py -> build/lib.linux-x86_64-2.7/pybombs/fetchers
creating build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/pkgconfig.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/base.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/yum.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/port.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/portage.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/pymod.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/pacman.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/brew.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/zypper.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/apt.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/pip.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/__init__.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/dummy.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/cmd.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/extern.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
copying pybombs/packagers/source.py -> build/lib.linux-x86_64-2.7/pybombs/packagers
creating build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/version.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/archives.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/output_proc.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/sysutils.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/vcompare.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/__init__.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/utils.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/tables.py -> build/lib.linux-x86_64-2.7/pybombs/utils
copying pybombs/utils/subproc.py -> build/lib.linux-x86_64-2.7/pybombs/utils
creating build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/prefix.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/distutils.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/empty.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/autoconf.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/setuptools.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/bjam.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/boostflags.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/bootstrapautoconf.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/sdk.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
copying pybombs/templates/cmake.lwt -> build/lib.linux-x86_64-2.7/pybombs/templates
creating build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/python.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/default_prefix.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/python-requests.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/graphviz.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/autoconf.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/cmake.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/build-essential.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/autotools-bootstrap.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/automake.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/xz.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
copying pybombs/recipes/git.lwr -> build/lib.linux-x86_64-2.7/pybombs/recipes
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/gitcache_manager.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/fetcher.py -> build/bdist.linux-x86_64/egg/pybombs
creating build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/base.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/rebuild.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/autoconfig.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/run.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/prefix.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/inv.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/deploy.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/fetch.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/lint.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/git.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/__init__.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/recipes.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/install.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/remove.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/help.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/config.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/commands/digraph.py -> build/bdist.linux-x86_64/egg/pybombs/commands
copying build/lib.linux-x86_64-2.7/pybombs/inventory.py -> build/bdist.linux-x86_64/egg/pybombs
creating build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/version.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/archives.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/output_proc.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/sysutils.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/vcompare.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/__init__.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/utils.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/tables.py -> build/bdist.linux-x86_64/egg/pybombs/utils
copying build/lib.linux-x86_64-2.7/pybombs/utils/subproc.py -> build/bdist.linux-x86_64/egg/pybombs/utils
creating build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/pkgconfig.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/base.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/yum.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/port.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/portage.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/pymod.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/pacman.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/brew.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/zypper.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/apt.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/pip.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/__init__.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/dummy.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/cmd.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/extern.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/packagers/source.py -> build/bdist.linux-x86_64/egg/pybombs/packagers
copying build/lib.linux-x86_64-2.7/pybombs/main.py -> build/bdist.linux-x86_64/egg/pybombs
creating build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/fetchers/base.py -> build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/fetchers/wget.py -> build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/fetchers/git.py -> build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/fetchers/svn.py -> build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/fetchers/__init__.py -> build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/fetchers/file.py -> build/bdist.linux-x86_64/egg/pybombs/fetchers
copying build/lib.linux-x86_64-2.7/pybombs/recipe.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/requirer.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/config_manager.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/install_manager.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/tree_node.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/pb_exception.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/__init__.py -> build/bdist.linux-x86_64/egg/pybombs
creating build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/python.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/default_prefix.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/python-requests.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/graphviz.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/autoconf.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/cmake.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/build-essential.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/autotools-bootstrap.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/automake.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/xz.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
copying build/lib.linux-x86_64-2.7/pybombs/recipes/git.lwr -> build/bdist.linux-x86_64/egg/pybombs/recipes
creating build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/prefix.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/distutils.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/empty.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/autoconf.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/setuptools.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/bjam.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/boostflags.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/bootstrapautoconf.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/sdk.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/templates/cmake.lwt -> build/bdist.linux-x86_64/egg/pybombs/templates
copying build/lib.linux-x86_64-2.7/pybombs/pb_logging.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/config_file.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/package_manager.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/recipe_manager.py -> build/bdist.linux-x86_64/egg/pybombs
copying build/lib.linux-x86_64-2.7/pybombs/dep_manager.py -> build/bdist.linux-x86_64/egg/pybombs
byte-compiling build/bdist.linux-x86_64/egg/pybombs/gitcache_manager.py to gitcache_manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetcher.py to fetcher.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/base.py to base.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/rebuild.py to rebuild.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/autoconfig.py to autoconfig.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/run.py to run.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/prefix.py to prefix.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/inv.py to inv.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/deploy.py to deploy.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/fetch.py to fetch.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/lint.py to lint.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/git.py to git.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/recipes.py to recipes.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/install.py to install.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/remove.py to remove.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/help.py to help.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/config.py to config.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/commands/digraph.py to digraph.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/inventory.py to inventory.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/archives.py to archives.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/output_proc.py to output_proc.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/sysutils.py to sysutils.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/vcompare.py to vcompare.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/tables.py to tables.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/utils/subproc.py to subproc.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/pkgconfig.py to pkgconfig.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/base.py to base.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/yum.py to yum.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/port.py to port.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/portage.py to portage.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/pymod.py to pymod.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/pacman.py to pacman.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/brew.py to brew.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/zypper.py to zypper.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/apt.py to apt.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/pip.py to pip.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/dummy.py to dummy.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/cmd.py to cmd.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/extern.py to extern.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/packagers/source.py to source.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetchers/base.py to base.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetchers/wget.py to wget.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetchers/git.py to git.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetchers/svn.py to svn.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetchers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/fetchers/file.py to file.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/recipe.py to recipe.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/requirer.py to requirer.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/config_manager.py to config_manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/install_manager.py to install_manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/tree_node.py to tree_node.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/pb_exception.py to pb_exception.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/pb_logging.py to pb_logging.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/config_file.py to config_file.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/package_manager.py to package_manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/recipe_manager.py to recipe_manager.pyc
byte-compiling build/bdist.linux-x86_64/egg/pybombs/dep_manager.py to dep_manager.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying PyBOMBS.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyBOMBS.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyBOMBS.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyBOMBS.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyBOMBS.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PyBOMBS.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pybombs.config_manager: module references __file__
creating dist
creating 'dist/PyBOMBS-2.3.3a0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PyBOMBS-2.3.3a0-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/PyBOMBS-2.3.3a0-py2.7.egg
Extracting PyBOMBS-2.3.3a0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding PyBOMBS 2.3.3a0 to easy-install.pth file
Installing pybombs script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/PyBOMBS-2.3.3a0-py2.7.egg
Processing dependencies for PyBOMBS==2.3.3a0
Searching for ruamel.yaml
Reading https://pypi.python.org/simple/ruamel.yaml/
Best match: ruamel.yaml 0.15.37
Downloading https://files.pythonhosted.org/packages/c1/ad/9557a78f1b61951623c56225e05dacdd81f80519f13fc39a926a5793edfa/ruamel.yaml-0.15.37.tar.gz#sha256=509842d96fb194f79b57483b76429f8956d8f7ade3cb49d1e5aeb5c5e9ef4918
Processing ruamel.yaml-0.15.37.tar.gz
Writing /tmp/easy_install-geulbw/ruamel.yaml-0.15.37/setup.cfg
Running ruamel.yaml-0.15.37/setup.py -q bdist_egg --dist-dir /tmp/easy_install-geulbw/ruamel.yaml-0.15.37/egg-dist-tmp-wuK8nn
sys.argv ['/tmp/easy_install-geulbw/ruamel.yaml-0.15.37/setup.py', '-q', 'bdist_egg', '--dist-dir', '/tmp/easy_install-geulbw/ruamel.yaml-0.15.37/egg-dist-tmp-wuK8nn']
error: Setup script exited with error in ruamel.yaml setup command: Invalid environment marker: platform_python_implementation=="CPython" and python_version<="2.7"
```

**Comment by mbr0wn** [comment] 2018-06-14 04:00
Not sure what's going on, but you might be able to workaround by installing ruamel.yaml through apt-get.

**Comment by mbr0wn** [comment] 2018-06-14 14:31
Ah, ruamel.yaml is not packaged for Jessie. Hm.

**Comment by mbr0wn** [comment] 2018-06-14 15:43
OK, I could reproduce. A workaround is to

    $ apt install python-dev
    $ pip install ruamel.yaml

Now, really, setup.py should do the exact same thing, so I'm not sure why the workaround works, but regular install does not. I'd appreciate some help here.

**Comment by mbr0wn** [comment] 2018-06-14 17:45
339c21c6f3c232521dab21bf29c92437f55cf31d

**Comment by cosinekitty** [comment] 2018-06-15 16:51
Thanks for providing a workaround, @mbr0wn!  I will give that a try this weekend.

**Comment by cosinekitty** [comment] 2018-06-18 02:20
Well, this is kinda dumb. Since I opened this issue, I forgot about it and went and upgraded to Debian Stretch 9.4.0. I suppose someone else still using Jessie might come here and find this useful though.

**Comment by mbr0wn** [comment] 2018-06-18 17:59
Did it work on Stretch?

**Comment by cosinekitty** [comment] 2018-06-19 01:35
I used the workaround before I thought about it, unfortunately. The pip install worked fine. Probably setup.py would have worked too, now that I’m on Stretch, but I didn’t think to try it. 

Don

**Comment by deinarson** [comment] 2018-08-06 02:35
I am new to pybombs, but for what it its worth, this seems to work.  At least with the docker's debian:jessie image.

If you are not using docker you can just manual running the commands removing the word "RUN"
[Dockerfile gist](https://gist.github.com/deinarson/9733841c48b411d8a32db5c216cdea1d)

So you might be able to close this. :)

**Comment by argilo** [comment] 2020-10-03 03:32
I'll close this off, since Debian Jessie is obsolete and no longer supported by PyBOMBS.

PyBOMBS appears to work well with Debian Buster.

**Closed by argilo** 2020-10-03 03:32 UTC
Labels: Debian, bug, help wanted
