### ISSUE TITLE
setup.py initial failure on Ubuntu-based systems

### ISSUE THREAD

**Issue by JonZeolla** [gnuradio/pybombs#251] opened 2016-02-07 05:08 UTC
I've tested this on Xubuntu, Lubuntu, and Ubuntu 14.04 and 15.10.  Below is specifically from a fresh install of Ubuntu 15.10:

`sudo apt-get install git cmake libboost-all-dev gnuradio-dev sox`
`sudo apt-get update`
`sudo apt-get upgrade`
`git clone --recursive https://github.com/gnuradio/pybombs`
`cd pybombs`

<img width="1086" alt="screen shot 2016-02-07 at 12 06 34 am" src="https://cloud.githubusercontent.com/assets/1385510/12870989/b1623902-cd2e-11e5-9d0e-6041c9f2f6aa.png">

If I simply run `sudo python setup.py install` a second time, it succeeds.

**Comment by mbr0wn** [comment] 2016-02-21 04:56
Was not able to reproduce this on a vanilla 14.04 VM.

**Comment by JonZeolla** [comment] 2016-02-21 12:51
This appears to be partially fixed.  Using the same commands as before, here is what I saw:

**Ubuntu 14.04 Desktop** completes successfully the first time ($? == 0), but on the first run there is a non-critical yaml.h error.  If I run a second time, I do not see this error.
<img width="987" alt="ubuntu 14 04 desktop error" src="https://cloud.githubusercontent.com/assets/1385510/13202609/aebb6070-d86e-11e5-8d83-c71a09bf4907.png">
<img width="760" alt="ubuntu 14 04 desktop try 1" src="https://cloud.githubusercontent.com/assets/1385510/13202586/e9e9096e-d86d-11e5-8108-3387b4fe2d48.png">

**Ubuntu 14.04 Server** completes successfully the first time ($? == 0), but on the first run there is a non-critical yaml.h error.  If I run a second time, I do not see this error.
<img width="1012" alt="ubuntu 14 04 server try 1" src="https://cloud.githubusercontent.com/assets/1385510/13202607/a00f2ae8-d86e-11e5-8881-8b63710a31ff.png">

**Ubuntu 15.10 Desktop** does not complete successfully the first time.  If I re-run `setup.py install` I get the non-critical yaml.h error, and if I run it a third time it looks clean.  
<img width="1106" alt="ubuntu 15 10 desktop try 1" src="https://cloud.githubusercontent.com/assets/1385510/13202587/f114c2e6-d86d-11e5-8cd9-3868145c7c16.png">
<img width="1082" alt="screen shot 2016-02-21 at 7 41 58 am" src="https://cloud.githubusercontent.com/assets/1385510/13202614/c096ba42-d86e-11e5-9c94-ed80bb7d5519.png">

**Ubuntu 15.10 Server** does not complete successfully the first time.  If I re-run `setup.py install` I get the non-critical yaml.h error, and if I run it a third time it looks clean.  
<img width="1038" alt="ubuntu 15 10 server try 1" src="https://cloud.githubusercontent.com/assets/1385510/13202608/a6975606-d86e-11e5-8da9-b4a3fb5bc696.png">

**Comment by mbr0wn** [comment] 2016-02-21 19:25
Does

    $ sudo pip install git+https://github.com/gnuradio/pybombs

throw the same error?

**Comment by mbr0wn** [comment] 2016-02-21 20:46
OK, git it now. There's an incompatibility with `ez_setup.py` and newer setuptools. I can apply a workaround, maybe, but it won't be a great solution, until someone fixes `ez_setup.py` (not me!).

**Comment by mbr0wn** [comment] 2016-02-21 21:27
Can't come up with a good workaround. At least, I improved the error message. FYI, `pip install` should always work if that's any help for you. Closing this as there's not much more I can do right now.

**Closed by mbr0wn** 2016-02-21 21:27 UTC

**Comment by mbr0wn** [comment] 2016-02-22 05:14
I found a newer version of ez_setup which seems to fix the issue.

**Comment by JonZeolla** [comment] 2016-02-22 12:02
Ok great, I assume that was 2a588d5.  I'll test later today

**Comment by JonZeolla** [comment] 2016-02-22 14:17
Confirmed - this seems to be resolved.  Thanks!
